### ISSUE TITLE
안녕하세요!

### ISSUE THREAD

**Issue by Foreist** [haven-jeon/PyKoSpacing#10]
개인적으로 띄어쓰기 모델에 관심이 있습니다.
pykospacing은 띄어쓰기 관련 모델을 논할 때 꼭 빠지지 않고 등장하는 모델이라 성능적인 측면에서 뛰어나고, 저도 이런 모델을 만들고 싶습니다.
그래서 처음에 pykospacing 저장소를 봤는데 아쉽게도 제가 학습을 시킨다거나 하는 건 불가능하고 사용만 할 수 있게 코드가 되어 있더라고요 ㅠㅠ
그런데 chatspace 소개글에서 pykospacing 커스텀모델이 있어서요!
그래서 혹시 저도 pykospacing 학습코드를 혹시 받아서 참조할 수 있을까 해서 연락드립니다.

**Comment by haven-jeon** [comment]
안녕하세요.

학습 코드가 있기는 한데, 너무 오래전 코드라서 공개를 위해서 손을 좀 봐야 됩니다. 다소 시간이 걸릴거 같네요. 

시간을 확정해드릴 수는 없지만, 노력해 보도록 하겠습니다.

감사합니다.

**Comment by haven-jeon** [comment]
다행히 큰 수정 없이 오픈 했습니다. 

아래 링크 참고하셔요.

https://github.com/haven-jeon/Train_KoSpacing

감사합니다.

**Comment by Foreist** [comment]
해당 이슈는 종료하도록 하겠습니다.
항상 만수무강하시고 좋은 일만 가득하셨으면 좋겠습니다.
감사합니다!
