### ISSUE TITLE
커널 멈춤 오류 질문드립니다.

### ISSUE THREAD

**Issue by myungchulkang** [haven-jeon/PyKoSpacing#14]
안녕하세요,

pykospcing을 사용 중에 있는 학생입니다.
우선 이렇게 좋은 패키지를 사용할 수 있도록 해주셔서 감사합니다.
쥬피터 노트북 환경에서 아무 이상 없이 잘 사용하던 도중,

```
!pip install git+https://github.com/haven-jeon/PyKoSpacing.git

from pykospacing import spacing
```

pykospacing을 임포트할 때 커널 멈춤 현상이 지속적으로 나타납니다.
혹시 어떤 문제인지 알 수 있을까요? 감사합니다.

**Comment by haven-jeon** [comment]
아래와 같이 colab에서 정상적으로 사용이 가능한걸 확인 했습니다.  

https://colab.research.google.com/drive/14fj222g-iqcISaSY1V0Itk0dtLIZWrVQ?usp=sharing

에러를 reproduce하지 못하면 도움을 드리기 어렵습니다.

**Comment by haven-jeon** [comment]
문제 없는 걸로 판단하고 close 하겠습니다.
