### ISSUE TITLE
불러오기 오류에 관하여 여쭤봅니다.

### ISSUE THREAD

**Issue by LeeKwanHyeong** [haven-jeon/PyKoSpacing#16]
![20201223_180605](https://user-images.githubusercontent.com/76516956/102984243-abfb3780-4550-11eb-8c3a-fa5fa0cbd68f.png)

라이브러리 다운로드는 되지만  import 시키면 오류가 뜹니다. 
AttributeError                            Traceback (most recent call last)
<ipython-input-8-6c5cf9e59f47> in <module>
----> 1 from pykospacing import spacing

~\anaconda3\envs\Lee\lib\site-packages\pykospacing\__init__.py in <module>
----> 1 from pykospacing.kospacing import *

~\anaconda3\envs\Lee\lib\site-packages\pykospacing\kospacing.py in <module>
     15 dic_path = pkg_resources.resource_filename(
     16     'pykospacing', os.path.join('resources', 'dicts', 'c2v.dic'))
---> 17 MODEL = load_model(model_path)
     18 MODEL.make_predict_function()
     19 W2IDX, _ = load_vocab(dic_path)

~\anaconda3\envs\Lee\lib\site-packages\tensorflow\python\keras\saving\save.py in load_model(filepath, custom_objects, compile, options)
    180     if (h5py is not None and (
    181         isinstance(filepath, h5py.File) or h5py.is_hdf5(filepath))):
--> 182       return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
    183 
    184     filepath = path_to_string(filepath)

~\anaconda3\envs\Lee\lib\site-packages\tensorflow\python\keras\saving\hdf5_format.py in load_model_from_hdf5(filepath, custom_objects, compile)
    174     if model_config is None:
    175       raise ValueError('No model found in config file.')
--> 176     model_config = json.loads(model_config.decode('utf-8'))
    177     model = model_config_lib.model_from_config(model_config,
    178                                                custom_objects=custom_objects)

AttributeError: 'str' object has no attribute 'decode'

**Comment by haven-jeon** [comment]
tensorflow 버전 이슈였습니다.

업데이트 했으니 사용에 큰 문제 없을 겁니다.

1a584e4938cabd18ec5f0cfd67956ced10649134

**Comment by LeeKwanHyeong** [comment]
네. 잘 됩니다!! 이렇게 빠르게 피드백 주셔서 너무 감사합니다. 잘 사용하겠습니다!!

**Comment by haven-jeon** [comment]
close 하겠습니다. ^^

**Comment by min0355** [comment]
텐서플로우 2.4.1 버전에선 똑같이 안 되네요. 
텐서 버전에 맞게 업데이트가 필요해 보이는데 조치 가능하실까요? 

ps. 멋진 한글 전 처리 패키지입니다.

**Comment by MonicaKim89** [comment]
텐서버전 떄문에 import가 계속 안되네요... gpu때문이라도 텐서버전을 업데이트 하기 힘든데 이런경우에는 어떻게 해야 사용할 수 있을까요?
