### ISSUE TITLE
PyKoSpacing 설치 문의

### ISSUE THREAD

**Issue by petershin89** [haven-jeon/PyKoSpacing#18]
안녕하세요! 
한국어 자연어 전처리 과정 중 PyKoSpacing 설치 중 이러한 메세지가 발생하여 혹시나 해결책을 조언 받을 수 있을까 하여 메세지 남깁니다.
에러 메세지는 다음과 같습니다.

ERROR: Could not find a version that satisfies the requirement tensorflow==2.4.0 (from pykospacing)
ERROR: No matching distribution found for tensorflow==2.4.0

제 tensorflow는 2.4.0 버전이 맞긴한데 2.4.0-rc0입니다.

>>> tf.__version__
'2.4.0-rc0'

혹시 이 건을 해결할 수 있는 조언을 구할 수 있을지 여쭙습니다.

감사합니다.

질문자 신동군 올림.

**Comment by haven-jeon** [comment]
https://github.com/haven-jeon/PyKoSpacing/blob/1a36be492cc396559e7dce7825843af020ea231f/setup.py#L18 에서 텐서플로 버전을 `2.4.0-rc0`로 교체하고 설치를 하시면 어떨까 합니다.

**Comment by haven-jeon** [comment]
답변에 대해서 별도 질의가 없어 해당 이슈 일단 클로즈 합니다.
