### ISSUE TITLE
구레나룻

### ISSUE THREAD

**Issue by elibooklover** [haven-jeon/PyKoSpacing#19]
좋은 패키지 제작 감사합니다.

'구레나룻'을 계속 spacing을 거치면 '구레나 룻'으로 변환됩니다.

**Comment by haven-jeon** [comment]
네... 이런 경우 룰엔진이 필요할거 같습니다. 

아래와 같은 방식 어떠신가요? 

```python
import re
s = "구레나룻"
p = re.compile('\s*'.join(s))
p.sub(s, '구레나 룻이 띄어써지네요.')
```

**Comment by haven-jeon** [comment]
피드백이 없어 해당 이슈는 클로즈 합니다.

**Comment by haven-jeon** [comment]
https://github.com/haven-jeon/PyKoSpacing#example 참고하세요.

**Comment by elibooklover** [comment]
감사합니다!
