### ISSUE TITLE
tensorflow==2.5.0 and keras bug

### ISSUE THREAD

**Issue by syncdoth** [haven-jeon/PyKoSpacing#23]
https://github.com/keras-team/keras/issues/14632

Related to the above issue, `tensorflow==2.5.0` is currently incompatible with the newest stable version of `keras==2.4.3`.

The proposed solution is to change `from keras import ...` to `from tensorflow.keras import ...`.

I found that https://github.com/haven-jeon/PyKoSpacing/blob/5256e826dc62565697215d567bf44988e9e2880f/pykospacing/embedding_maker.py#L1 is the  line causing this issue: could you please handle this problem?

**Comment by haven-jeon** [comment]
Thanks for letting us know about an important issue. 

7bd81fe9c55a54e1b8e6f6bd5931b87bec98784f
