### ISSUE TITLE
rules 정규표현식 적용

### ISSUE THREAD

**Issue by jungsiroo** [haven-jeon/PyKoSpacing#34]
안녕하세요 PyKoSpacing 쓰던 도중 질문이 생겨 질문드립니다!

`abcd1234@gmail.com` 을 `abcd 1234@gmail .com` 으로 spacing 이 진행되는데 rules 에 정규표현식을 써서 스페이싱이 안되게 할 수 있을까요??

**Comment by haven-jeon** [comment]
현재 rules에 입력되는 텍스트로 동적 regex를 생성하는 방식으로 적용하고 있어서 말씀하신 룰은 현재로서 적용하기 어렵습니다. 다만.. 입력 텍스트의 email 을 미리 regex로 특수 문자로 replace해놓으시고 띄어쓰기 동작한 뒤에 해당 특수 문자를 원래 이메일 주소로 변환하시는 전처리 로직을 진행하면 어떨까 합니다.

**Comment by jungsiroo** [comment]
@haven-jeon 친절한 답변 너무 감사드립니다! 전처리 방식을 고민해봐야겠네요,,, 감사합니다!
