### ISSUE TITLE
텐서플로우 2.6.4가 설치가 안 됩니다.

### ISSUE THREAD

**Issue by gembleman** [haven-jeon/PyKoSpacing#39]
pip install tensorflow==2.6.4
ERROR: Could not find a version that satisfies the requirement tensorflow==2.6.4 (from versions: 2.8.0rc1, 2.8.0, 2.8.1, 2.8.2, 2.9.0rc0, 2.9.0rc1, 2.9.0rc2, 2.9.0, 2.9.1)
ERROR: No matching distribution found for tensorflow==2.6.4
파이썬 64비트 3.10버전을 쓰고 있는데 이 버전이 텐서플로우가 지원하지 않는 버전인가 봅니다.
PyKoSpacing에서 텐서플로우 버전을 올려주시기를 부탁드립니다.

**Comment by haven-jeon** [comment]
답변이 없으셔서 해당 이슈 클로즈 합니다.

**Comment by gembleman** [comment]
깃허브 알림 메일이 스팸함으로 가고 있어서 이제야 봤네요.
답변 늦어져서 죄송합니다. 잘 되는 거 확인했습니다. 고맙습니다!

**Comment by dodoyeon** [comment]
안녕하세요 같은 문제로 여기에 이슈를 남깁니다.
pip install tensorflow==2.6.4 가 버전 지원이 안되서 사용을 못하고 있는데
#36 을 올려주신게 이해가되지 않습니다. 
머지되었다는 버전인
pip install tensorflow==2.7.2 도 버전지원이 안되는데 혹시 어떻게 해결하면 좋을지 여쭤봐도 될까요?

**Comment by haven-jeon** [comment]
테스트 해봤는데, 정상 동작합니다. 


<img width="604" alt="image" src="https://user-images.githubusercontent.com/957840/209738077-443c9c9c-e843-46fd-ac18-2b73c1ccbe39.png">

실행 환경과 에러 출력 결과 등 정보 확인 부탁드립니다.
