### ISSUE TITLE
How to add some new words to the training corpus?

### ISSUE THREAD

**Issue by sunparkmos** [haven-jeon/PyKoSpacing#4]
s20통장을쏠편한입출금으로 전환 => current result => s20 통장을 쏠 편한 입출금으로 전환
s20통장을쏠편한입출금으로 전환 => I'd like to below => s20통장을 쏠편한 입출금으로 전환

**Comment by haven-jeon** [comment]
Even if you insert the learning data, it is difficult for the issue to be solved. Rather, there is also a risk that the overall performance of the model will decline when it tries to learn. For these patterns, it may be effective to set up post-processing rules for the sentence.

**Comment by sunparkmos** [comment]
Thank you for your quick reply,
What are the post processing rules for the sentences? Could you explain it more?
쏠편한 is a new product name by a bank.
I thought the following way to correct from "쏠 편한", after Kospacing to "쏠편한".
Look for the pattern "쏠 편한" in the resulting sentence, and then then change to "쏠편한".
Do you have other ways, then pls let me know them,

**Comment by haven-jeon** [comment]
Perhaps there are various patterns of pykospacing results. So we need to consider the changes in these.

>> "쏠 편한", "쏠편 한", "쏠 편 한"

The larger the dictionary, the more likely it will be a performance issue, but the code below might be the starting point of post processing.

```{python}
>> import re
>> s = "쏠편한" # word in user dictionary 
>> p = re.compile('\s*'.join(s))
>> p.sub(s, 's20 통장을 쏠 편한 입출금으로 전환')
's20 통장을 쏠편한 입출금으로 전환'
```

**Comment by sunparkmos** [comment]
Good idea
