### ISSUE TITLE
module 'importlib.abc' has no attribute 'ResourceReader' 오류가 뜹니다

### ISSUE THREAD

**Issue by SpringCat9** [haven-jeon/PyKoSpacing#41]
import 시에 난 에러입니다

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-24-4844cec29dd1> in <module>
      3 from PIL import ImageGrab
      4 
----> 5 from pykospacing import Spacing
      6 import importlib.abc
      7 spacing = Spacing()

~\anaconda3\envs\TF21\lib\site-packages\pykospacing\__init__.py in <module>
----> 1 from pykospacing.kospacing import *

~\anaconda3\envs\TF21\lib\site-packages\pykospacing\kospacing.py in <module>
      6 
      7 import numpy as np
----> 8 import pkg_resources
      9 from tensorflow.keras.models import load_model
     10 from pykospacing.embedding_maker import encoding_and_padding, load_vocab

~\anaconda3\envs\TF21\lib\site-packages\pkg_resources\__init__.py in <module>
     72     importlib_machinery = None
     73 
---> 74 from pkg_resources.extern.jaraco.text import (
     75     yield_lines,
     76     drop_comment,

~\anaconda3\envs\TF21\lib\site-packages\pkg_resources\_vendor\jaraco\text\__init__.py in <module>
      5 
      6 try:
----> 7     from importlib.resources import files  # type: ignore
      8 except ImportError:  # pragma: nocover
      9     from pkg_resources.extern.importlib_resources import files  # type: ignore

~\anaconda3\envs\TF21\lib\importlib\resources.py in <module>
     65 
     66 def _get_resource_reader(
---> 67         package: ModuleType) -> Optional[resources_abc.ResourceReader]:
     68     # Return the package's loader if it's a ResourceReader.  We can't use
     69     # a issubclass() check here because apparently abc.'s __subclasscheck__()

AttributeError: module 'importlib.abc' has no attribute 'ResourceReader'

**Comment by haven-jeon** [comment]
제 머신에서 재현이 가능하지 않는데, 오류가 난 환경 설명 부탁드립니다.

**Comment by haven-jeon** [comment]
답변이 없으셔서 일단 해당 이슈는 클로즈 합니다.
