### ISSUE TITLE
사용자 지정 단어 설정 여부

### ISSUE THREAD

**Issue by gloriakim-arch** [haven-jeon/PyKoSpacing#43]
같은 단어여도 띄어쓰기가 다르게 적용될 때가 있는 것 같습니다.
예를 들어서 "제주도"라는 단어를 처리할 때 "제주도"라고 잘 될 때도 있지만, "제주 도"처럼 띄어쓰기 될 때도 있는데 혹시 특정 단어를 사용자가 지정해서 띄어쓰기하지 못하도록 설정할 수 있나요?

**Comment by haven-jeon** [comment]
https://github.com/haven-jeon/PyKoSpacing#example 에 보시면 rules에 지정 가능합니다.

**Comment by gloriakim-arch** [comment]
답변 감사합니다:) 말씀해주신 대로 적용해 보았는데, 다른 기능에 대한 질문이 생겼습니다. 특정 단어는 무조건 앞 뒤로 띄어쓰기 될 수 있게 지정할 수도 있을까요? 예를 들어 "제주도와플"이라는 두 개 명사가 붙어 있을 경우, 무조건 "제주도 와플"로 띄어쓰기하게 할 수 있을지요?

**Comment by haven-jeon** [comment]
이런 처리는 전,후처리를 해주시면 됩니다.  
`제주도와플`을 모두 붙여쓰게 룰을 적용하고 `replace('제주도와플', '제주도 와플')`로 후처리 하시면 간단하게 해결될듯 합니다

**Comment by haven-jeon** [comment]
별도 답변이 없으셔서 해당 이슈는 클로즈 합니다. 필요시 다시 열어주셔요 .
