### ISSUE TITLE
출력 화면 간소화 

### ISSUE THREAD

**Issue by skyshower** [haven-jeon/PyKoSpacing#46]
안녕하세요. 좋은 패키지 만들어주셔서 먼저 감사하단 말씀을 드리고 싶습니다.

다름이 아니라 패키지 사용 중에 학습 진행 막대가 출력이 되는데(verbose=1), 이를 뜨지 않게 할 수 있을까요?

**Comment by sml8648** [comment]
kospacing.py의 68번째줄을 수정하면 해결이 되네요!
results = self._model.predict(mat_in) => results = self._model.predict(mat_in, verbose=0)

**Comment by skyshower** [comment]
> 저도 해당 부분이 불편했는데 kospacing.py의 68번째줄을 수정하면 해결이 되네요! results = self._model.predict(mat_in) => results = self._model.predict(mat_in, verbose=0)



해결됐습니다. 정말 감사드립니다!

**Comment by haven-jeon** [comment]
@sml8648 @skyshower  

올려주신 코드를 메인 코드에 커밋 완료 했습니다.  앞으로는 편하게 PR 주시면 좋을거 같아요. ^^
