### ISSUE TITLE
m1 환경에서 모듈 불러오기 오류

### ISSUE THREAD

**Issue by JONGSKY** [haven-jeon/PyKoSpacing#47]
안녕하세요! 먼저 좋은 모듈 만들어주셔서 감사드립니다.

PyKoSpacing 모듈로 띄어쓰기 전처리를 진행하려고 하던 도중 이슈가 생겨서 문의드립니다.

현재 m1 맥북을 사용해서 모듈을 설치했으나,
모듈을 불러오는 과정에서 커널이 꺼지는 현상이 있어 문의드립니다.

<img width="525" alt="image" src="https://user-images.githubusercontent.com/40276516/215261512-9dd21dfd-a461-42fa-9ce9-9d79309fffb2.png">

<img width="906" alt="image" src="https://user-images.githubusercontent.com/40276516/215261556-dc9bd8e3-3833-4915-b15e-9407f5e61d4e.png">

감사합니다.

**Comment by haven-jeon** [comment]
안타깝게도 제가 M1 환경을 가지고 있지 못해서 테스트가 어렵습니다. 
혹시 개선 방향 찾으시면 공유 부탁드리겠습니다.

**Comment by JONGSKY** [comment]
PyKoSpacing 모듈 설치에 필요한
tersorflow, keras에서 오류가 나는 것으로 확인했습니다.

<img width="515" alt="image" src="https://user-images.githubusercontent.com/40276516/215299453-0ea4c0ff-cee3-4c76-9147-75844f66c68f.png">

저는 m1, anaconda 가상환경에서 실행했었느데
확인해본 결과 m1, anconda에서는 m1과 호환성 문제가 있다고 합니다.

따라서 miniforge를 사용해서 tersorflow, keras를 설치하였으나, ([설치방법](https://jongsky.tistory.com/34))
<img width="570" alt="image" src="https://user-images.githubusercontent.com/40276516/215300937-25db002e-f2d5-4101-88ce-618a9b09fbbe.png">

설치 과정에서 setup.py에서 install_requires가 설정되어 오류가 나는 문제가 있었습니다.
그래서 os별 호환성을 위해 해당 내용을 삭제했으며 requirements.txt에도 주석처리했더니 해결되었습니다.

<img width="520" alt="image" src="https://user-images.githubusercontent.com/40276516/215301165-682f9dc4-c344-4cce-9b2d-6687b43505af.png">

**Comment by JONGSKY** [comment]
[setup.py.zip](https://github.com/haven-jeon/PyKoSpacing/files/10528832/setup.py.zip)

변경한 setup.py 파일 공유드리며, requirements.txt는 모두 주석처리했습니다.

**Comment by haven-jeon** [comment]
setup.py, requirements.txt 등 PR 부탁드려도 될까요?

**Comment by haven-jeon** [comment]
머지 되서 클로즈 합니다.
