### ISSUE TITLE
Can the model output probability？

### ISSUE THREAD

**Issue by treya-lin** [haven-jeon/PyKoSpacing#53]
Can we get the probability for the spacing results from the model so that I can maybe manually check the results with lower probability? Thanks a lot!!

**Comment by haven-jeon** [comment]
This line can be a clue for your request.

https://github.com/haven-jeon/PyKoSpacing/blob/5bb0b3e8f62c1936a430745297821a9ecd78beb1/pykospacing/kospacing.py#L70
