### ISSUE TITLE
google colab에서 !pip install시 에러 발생. 

### ISSUE THREAD

**Issue by chobbong** [haven-jeon/PyKoSpacing#54]
google colab에서 !pip install시 에러 발생합니다. 

!pip install git+https://github.com/haven-jeon/PyKoSpacing.git

-----------------------(error message)---------------------------
NotImplementedError                       Traceback (most recent call last)
[<ipython-input-11-74e6ddf0af84>](https://localhost:8080/#) in <cell line: 1>()
----> 1 get_ipython().system('pip install git+https://github.com/haven-jeon/PyKoSpacing.git')

2 frames
[/usr/local/lib/python3.10/dist-packages/google/colab/_system_commands.py](https://localhost:8080/#) in _run_command(cmd, clear_streamed_output)
    165   locale_encoding = locale.getpreferredencoding()
    166   if locale_encoding != _ENCODING:
--> 167     raise NotImplementedError(
    168         'A UTF-8 locale is required. Got {}'.format(locale_encoding)
    169     )

NotImplementedError: A UTF-8 locale is required. Got ANSI_X3.4-1968
----------------------------------------------------------------------------------
이를 어떻게 해결해야 할까요? 

system : window-10 
GPU : 엔비디아 3060

**Comment by rustic-snob** [comment]
!pip install 뒤에 --no-deps argument를 추가해보세요.
h5py 3.1.0 버전 설치 중에 오류가 나는 것 같습니다.

**Comment by haven-jeon** [comment]
#55 참고하세요. 

클로즈 합니다.
