### ISSUE TITLE
google colab - pip install error

### ISSUE THREAD

**Issue by AhyunHeo** [haven-jeon/PyKoSpacing#55]
google colab에서 !pip install 시 다음과 같은 에러가 발생합니다. 해결 방법이 있을까요??

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting git+https://github.com/haven-jeon/PyKoSpacing.git
  Cloning https://github.com/haven-jeon/PyKoSpacing.git to /tmp/pip-req-build-s3ixwel_
  Running command git clone --filter=blob:none --quiet https://github.com/haven-jeon/PyKoSpacing.git /tmp/pip-req-build-s3ixwel_
  Resolved https://github.com/haven-jeon/PyKoSpacing.git to commit 5bb0b3e8f62c1936a430745297821a9ecd78beb1
  Preparing metadata (setup.py) ... done
Collecting tensorflow==2.9.3 (from pykospacing==0.5)
  Downloading tensorflow-2.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.8/511.8 MB 2.4 MB/s eta 0:00:00
Collecting h5py==3.1.0 (from pykospacing==0.5)
  Downloading h5py-3.1.0.tar.gz (371 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 371.4/371.4 kB 22.2 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing backend dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by SoyoungJun-SL** [comment]
!pip install git+https://github.com/haven-jeon/PyKoSpacing.git --no-deps argument

아래 이슈 답변이었는데 시도해보니 잘 설치되네요

**Comment by SoyoungJun-SL** [comment]
!pip install git+https://github.com/haven-jeon/PyKoSpacing.git --no-deps argument

아래 이슈 답변 참고하여 시도해보니 잘 작동하네요~

**Comment by haven-jeon** [comment]
네 감사합니다. 클로즈 합니다.
