### ISSUE TITLE
코랩에서 패키지 설치시 subprocess-exited-with-error 

### ISSUE THREAD

**Issue by pinksoya** [haven-jeon/PyKoSpacing#57]
안녕하세요 코랩에서 이 패키지를 설치하려고 하면 이런 에러가 납니다..
어떻게 하면 좋을까요?

!pip install git+https://github.com/haven-jeon/PyKoSpacing.git

Collecting git+https://github.com/haven-jeon/PyKoSpacing.git
  Cloning https://github.com/haven-jeon/PyKoSpacing.git to /tmp/pip-req-build-sy_445dq
  Running command git clone --filter=blob:none --quiet https://github.com/haven-jeon/PyKoSpacing.git /tmp/pip-req-build-sy_445dq
  Resolved https://github.com/haven-jeon/PyKoSpacing.git to commit 5bb0b3e8f62c1936a430745297821a9ecd78beb1
  Preparing metadata (setup.py) ... done
Collecting tensorflow==2.9.3 (from pykospacing==0.5)
  Downloading tensorflow-2.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.8/511.8 MB 2.4 MB/s eta 0:00:00
Collecting h5py==3.1.0 (from pykospacing==0.5)
  Downloading h5py-3.1.0.tar.gz (371 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 371.4/371.4 kB 18.6 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing backend dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

![image](https://github.com/haven-jeon/PyKoSpacing/assets/65769727/518434bd-db00-449e-9c80-c1573bc25507)

**Comment by haven-jeon** [comment]
https://github.com/haven-jeon/PyKoSpacing/issues/55#issue-1770879381 참고하세요.

**Comment by pinksoya** [comment]
감사합니다. 오류없이 잘 설치되었습니다.
