### ISSUE TITLE
안녕하세요 colab에서 개발자님께서 만든 라이브러리를 설치하는 과정 중에 오류가 발생하여 문의드려봅니다.

### ISSUE THREAD

**Issue by JunBeomPark1120** [haven-jeon/PyKoSpacing#59]
!pip install git+https://github.com/haven-jeon/PyKoSpacing.git
해당 코드를 실행하는 과정에서
Collecting git+https://github.com/haven-jeon/PyKoSpacing.git
  Cloning https://github.com/haven-jeon/PyKoSpacing.git to /tmp/pip-req-build-fvh_57a6
  Running command git clone --filter=blob:none --quiet https://github.com/haven-jeon/PyKoSpacing.git /tmp/pip-req-build-fvh_57a6
  Resolved https://github.com/haven-jeon/PyKoSpacing.git to commit d1e2f93759b1bcc74b6aaa345a62c08701e5546e
  Preparing metadata (setup.py) ... done
Collecting tensorflow==2.9.3 (from pykospacing==0.5)
  Downloading tensorflow-2.9.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (511.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 511.8/511.8 MB 3.2 MB/s eta 0:00:00
Collecting h5py==3.1.0 (from pykospacing==0.5)
  Downloading h5py-3.1.0.tar.gz (371 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 371.4/371.4 kB 28.3 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  error: subprocess-exited-with-error
  
  × pip subprocess to install backend dependencies did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Installing backend dependencies ... error
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

이러한 오류 메시지가 출력되었습니다. 혹시 해결가능한 부분이 있을까 해서 문의 드려봅니다. tensorflow와 h5py도 최신버전으로 업데이트 했지만 이유를 잘 모르겠습니다.

**Comment by DoYoungNim** [comment]
저도 동일한 오류가 뜹니다. 놓친 설정이나 해결 방법이 있을까요?

**Comment by kyy1217** [comment]
안녕하세요, 저도 계속 동일한 오류가 발생합니다. 
버전 호환을 시켜도 안돼서 혹시 해결 방법이 있을지 문의드리고 싶습니다.
감사합니다. 
![image](https://github.com/haven-jeon/PyKoSpacing/assets/123720268/198946d0-e053-457d-a924-0d65a8aa213d)

**Comment by haven-jeon** [comment]
https://github.com/haven-jeon/PyKoSpacing/commit/04aeebcbe26b109486a642e57dc58665c4818cf3

새로 설치/테스트 해보시면 동작할겁니다. 

![image](https://github.com/haven-jeon/PyKoSpacing/assets/957840/5db19d48-9944-4377-b64d-0e2ff986ba36)

**Comment by kyy1217** [comment]
개발자님 안녕하세요,

오늘 다시 진행해보니 돌아갑니다.
너무 감사합니다. 

항상 많이 배우고 있습니다. 감사합니다.
그럼 오늘도 좋은 하루 보내세요. 



네이버 메일앱에서 보냈습니다.
-----Original Message-----
보낸사람: "Heewon ***@***.***>
받는사람: ***@***.***>
참조: "yuyeong ***@***.***>, ***@***.***>
날짜: 2023. 11. 21 오후 12:41:24
제목: Re: [haven-jeon/PyKoSpacing] 안녕하세요 colab에서 개발자님께서 만든 라이브러리를 설치하는 과정 중에 오류가 발생하여 문의드려봅니다. (Issue #59)

04aeebc
새로 설치/테스트 해보시면 동작할겁니다.

**Comment by haven-jeon** [comment]
감사합니다. 
해당 이슈 클로징 합니다. ^^
