### ISSUE TITLE
Has anyone tried it on Windows?

### ISSUE THREAD

**Issue by Jasas9754** [haven-jeon/PyKoSpacing#6]
```
(pykospacing) C:\Users\xxxx>python -m pykospacing.pykos -o "xxxx\test_in.txt" "xxxx\test_out.txt"
Using TensorFlow backend.

(pykospacing) C:\Users\xxxx>
```
Env:Anaconda py3.6 Window 10 pro

I have tested tensorflow 1.4.0~1.6.0 but none of them works.
Nothing appears but a blank space.

**Comment by haven-jeon** [comment]
Most of install problem is cause by specific user setting(like PYTHONPATH...). I strongly recommand to check installed packages what PyKoSpacing requires.

**Comment by haven-jeon** [comment]
Might be related with this commit.

https://github.com/haven-jeon/PyKoSpacing/pull/7
