### ISSUE TITLE
future version release? (Keras v3 support)

### ISSUE THREAD

**Issue by m4a1carbin4** [haven-jeon/PyKoSpacing#62]
It appears that TensorFlow has officially transitioned to Keras 3 as of version 2.16. However, it is uncertain whether the model for this project will function correctly in the TensorFlow Keras 3 backend environment.

I attempted to use this project with TensorFlow version 2.16, the official version that supports Python 3.12, because my personal project's Python environment is version 3.12. However, critical issues arise during the model loading process.

For this reason, I am curious if there are any future plans to ensure compatibility of this model with Keras 3.

**Comment by haven-jeon** [comment]
I acknowledge this as a critical issue and are actively looking into solutions.

A possible short-term workaround for the 2.15 version involves converting the existing binaries to the H5 format. I've completed the initial conversion step but haven't yet had a chance to fully test the performance impact.

If you're able to contribute a PR related to this workaround or any other potential fixes, it would be greatly appreciated.

**Comment by haven-jeon** [comment]
I tested it and confirmed that it works well. Thank you so much for your work.

**Comment by m4a1carbin4** [comment]
Thanks!
