### ISSUE TITLE
설치시 python setup.py egg_info 문제

### ISSUE THREAD

**Issue by sundoforce** [haven-jeon/PyKoSpacing#8]
ERROR: Command "python setup.py egg_info" failed with error code -4 in /tmp/pip-req-build-gaelx667/

안녕하세요.

의존성 
python3 
tensorflow 1.6
keras 

모두 설치 했는데 

 pip install git+https://github.com/haven-jeon/PyKoSpacing.git
하면 에러가 납니다.

centos7 
ubuntu16.04 ~ 18.04 

동일합니다.

pip버전은 아래와 같습니다.

root@2ee74d3f11bd:/home/sdk# pip install -U pip
Requirement already up-to-date: pip in /usr/local/lib/python3.6/dist-packages (19.1.1)
root@2ee74d3f11bd:/home/sdk# pip --version
pip 19.1.1 from /usr/local/lib/python3.6/dist-packages/pip (python 3.6)

**Comment by supermusha** [comment]
동일 문제 발생 중인데 close 된걸로 보아 해결된 것 같은데, 방법을 알수 있을까요? 아니면 아직 버전 업데이트가 안되었을지요?
