### ISSUE TITLE
how to makd model for me???

### ISSUE THREAD

**Issue by ssifood** [haven-jeon/PyKoSpacing#9]
모델을 만들려면 어떻게 해야 하나요?
what shoud i do for making model??

찾아보니 모델을 못만드는것 같은데요. 맞나요?

감사합니다.

**Comment by haven-jeon** [comment]
이 레포에는 학습 코드는 없습니다. 비밀이라 할 것도 없는데, 공개할만큼 정리가 잘 안되어 있어서 공개를 못하고 있네요... 양해 부탁드립니다.

**Comment by haven-jeon** [comment]
https://github.com/haven-jeon/Train_KoSpacing 참고하시길 바랍니다.
